POST  http://localhost:5000/CustomerLogin
Content-Type: application/json

{
   

"email":"john@j.com",
"password":"jjj"


}

# PUT http://localhost:5000/CustomerSchemeEdit
# Content-Type: application/json

# {
#    "jewellerid":"80q6vbYm0",
#    "schemeid":"h3zFn1e4q",
#  "customerid":"yEp7ztSkX",
#  "loanstatus_jw":"yes"
# }



# GET http://localhost:5000/CustomerSchemesLoanReq
# Content-Type: application/json